---
- name: Update all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install packages
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "vim"
      - "tmux"
      - "gnupg-agent"
      - "software-properties-common"
      - "python3-psycopg2"
      - "nginx"
      - "fail2ban"
      - "podman"
