---
- name: Flush iptables
  iptables:
    flush: yes

- name: Allow incoming ssh
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ sshd_port_number }}"
    jump: ACCEPT

- name: Allow all outgoing traffic
  iptables:
    chain: OUTPUT
    jump: ACCEPT

- name: Drop all incoming traffic
  iptables:
    chain: INPUT
    policy: DROP

- name: Allow tcp ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
    jump: ACCEPT